# load data 

In [2]:
import h5py
import numpy as np

In [3]:
redshift = np.loadtxt('/home/yunzheng/mock/orphan/redshift.txt')

In [210]:
redshift[92]

0.2182580231028184

# 选取snapshot92来做mocktest

## 存subhaloid、速度vmax、subhalo出现的snapshot

In [67]:
sub_file = h5py.File('/home/cossim/CosmicGrowth/6610/subcat2/SubSnap_009.hdf5','r')['Subhalos'][...]
subid = sub_file['TrackId']
vmax = sub_file['VmaxPhysical']
birthsnap = sub_file['SnapshotIndexOfBirth']

In [68]:
subid

array([   0,    1,    2, ..., 9055, 9056, 9057])

In [69]:
vmax

array([207.93156 ,   0.      , 180.1976  , ..., 102.518555, 125.204865,
       112.25584 ], dtype=float32)

In [70]:
birthsnap

array([0, 0, 0, ..., 9, 9, 9], dtype=int32)

In [71]:
a = np.stack((subid,vmax,birthsnap),axis= -1)

In [72]:
a.shape

(9058, 3)

In [73]:
print("the length of subid is %d"%(len(subid)))

the length of subid is 9058


In [75]:
 b = np.load('/home/yunzheng/mock/color/data/vmax/snapshot_9.npy')

In [77]:
b.shape

(9058, 3)

In [26]:
xxx = range(10,50)

In [33]:
xxx[39]

49

## 在所有subhalo vmax中找到orphan与subhalo table相应的id

In [5]:
subhalo = np.loadtxt('/home/yunzheng/mock/subhalos_new/subhalotable/snapshot_%s.txt'%92)
orphan = np.load('/home/yunzheng/mock/orphan_new/final_selection_new/snapshot_%s/orphantable_final.npy'%92)

In [6]:
len(subhalo)

23086613

In [80]:
len(orphan) + len(subhalo)

26241654

In [86]:
orphan.shape

(3155041, 12)

In [8]:


subid = np.concatenate((subhalo[:,0], orphan[:,0]))

vpeak = np.concatenate((subhalo[:,4], orphan[:,4]))

vpeaksnap = np.concatenate((subhalo[:,5], orphan[:,5]))
    

In [56]:
subid = np.array(subid,dtype = int)

In [90]:
subid[:10]

array([ 2,  3,  4,  7,  8,  9, 12, 13, 15, 20])

In [83]:
orp_mass = np.ones(len(orphan)) * 0.05541996

In [85]:
orp_mass.shape

(3155041,)

In [184]:
subhalo[0][5]

53.0

In [171]:
vpeaksnap = np.array(vpeaksnap,dtype = 'int')

In [170]:
vpeaksnap[10]

51

In [12]:
len_all = np.loadtxt('/home/yunzheng/mock/color/data/len_all.txt')

In [53]:
len_all[:5]

array([  3.,  13.,  33.,  82., 212.])

In [187]:
vmax = []
for i in range(100):
    v = np.load('/home/yunzheng/mock/color/data/vmax/snapshot_%s.npy'%i)
    vmax.append(v)

KeyboardInterrupt: 

In [228]:
vmax[2]

array([[  0.        , 138.88401794,   0.        ],
       [  1.        , 109.96416473,   0.        ],
       [  2.        , 173.0643158 ,   0.        ],
       [  3.        , 114.61103821,   1.        ],
       [  4.        , 140.35394287,   1.        ],
       [  5.        , 109.96416473,   1.        ],
       [  6.        , 155.51281738,   1.        ],
       [  7.        , 135.61853027,   1.        ],
       [  8.        , 130.37728882,   1.        ],
       [  9.        , 109.96416473,   1.        ],
       [ 10.        , 145.68585205,   1.        ],
       [ 11.        , 151.6381073 ,   1.        ],
       [ 12.        , 111.9177475 ,   1.        ],
       [ 13.        , 112.90650177,   2.        ],
       [ 14.        , 109.96416473,   2.        ],
       [ 15.        , 120.92839813,   2.        ],
       [ 16.        , 126.07809448,   2.        ],
       [ 17.        , 109.96416473,   2.        ],
       [ 18.        , 122.42756653,   2.        ],
       [ 19.        , 109.96416

In [144]:
vmax_evo = []

In [ ]:
vmax_evo.append(vmax)

In [248]:
z_form = []
for i in range(20):
    vform =  vpeak[i] * 0.75
    print('The vpeak is %s'%(vpeak[i]))
    print('The vform is %s'%(vform))
    print('The vpeak snapshot is %s'%vpeaksnap[i])
    for j in range(100):
        if subid[i] <= len_all[j] -1:
            print('The birthsnap of %dth subhalo is %d'%(subid[i],j))
            print('The birthsnap check is %d'%(vmax[j][subid[i]][2]))
            print('j = %d'%j)

            for k in range(j,vpeaksnap[i]):
                
#                 vmax_evo = vmax[k][subid[i]][1]
#                 print('The vmax is %s'%vmax_evo)
#                 vmax_evo_1 = vmax[k+1][subid[i]][1]
#                 print('The vmax of next snapshot is %s'%vmax_evo_1)
                
                if vform < vmax[k][subid[i]][1]:
                    snap_bir = j
                    print('The snapshot of birth is %s'%snap_bir)
                    print('The vmax is %s'%vmax[k][subid[i]][1])
                    z_form = redshift[j]
                    print('The redshift is %s'%z_form)
                    break
#                 elif vmax_evo <= vform < vmax_evo_1 :
                elif vmax[k][subid[i]][1] <= vform < vmax[k+1][subid[i]][1]:
#                     snap_bir = k
                    print('The snapshot of interpretation is between %s and %s .'%(k,k+1))
                    print('The first redshift is %s'%(redshift[k]))
                    print('The next redshift is %s'%(redshift[k+1]))
                    print('The first vmax is %s'%(vmax[k][subid[i]][1]))
                    print('The next vmax is %s'%(vmax[k+1][subid[i]][1]))
                    interp_v = [vmax[k][subid[i]][1],vmax[k+1][subid[i]][1]]
                    interp_z = [redshift[k],redshift[k+1]]
                    red_new = np.interp(vform,interp_v,interp_z)
#                     form_all = np.array((subid[i],vpeak[i],vpeaksnap[i],vform,red_new))
#                     z_form.append(form_all)
                    print('The interplated redshift is %s'%red_new)
                    break
#                 print('The circle number is %s'%k)
            form_all = np.array((subid[i],vpeak[i],vpeaksnap[i],vform,red_new))
            z_form.append(form_all)
#             print('j = %d'%j)
            break
# print(z_form)
        
            

        




The vpeak is 306.27947998046875
The vform is 229.70960998535156
The vpeak snapshot is 53
The birthsnap of 2th subhalo is 0
The birthsnap check is 0
j = 0
The snapshot of interpretation is between 14 and 15 .
The first redshift is 10.60817231932476
The next redshift is 10.24519172362668
The first vmax is 214.13926696777344
The next vmax is 254.34100341796875
The interplated redshift is 10.467588034097536
The vpeak is 489.8222351074219
The vform is 367.3666763305664
The vpeak snapshot is 88
The birthsnap of 3th subhalo is 1
The birthsnap check is 1
j = 1
The snapshot of interpretation is between 49 and 50 .
The first redshift is 3.1447514243462287
The next redshift is 3.0254516503041575
The first vmax is 360.27398681640625
The next vmax is 368.58148193359375
The interplated redshift is 3.0428968647643337
The vpeak is 439.2156066894531
The vform is 329.41170501708984
The vpeak snapshot is 87
The birthsnap of 4th subhalo is 1
The birthsnap check is 1
j = 1
The snapshot of interpretation is

In [243]:
z_form_test = z_form

In [250]:
z_form

[array([  2.        , 306.27947998,  53.        , 229.70960999,
         10.46758803]),
 array([  3.        , 489.82223511,  88.        , 367.36667633,
          3.04289686]),
 array([  4.        , 439.21560669,  87.        , 329.41170502,
          7.05297605]),
 array([  7.        , 426.41589355,  87.        , 319.81192017,
          1.97862841]),
 array([  8.        , 678.11975098,  88.        , 508.58981323,
          3.39115355]),
 array([  9.        , 496.75585938,  91.        , 372.56689453,
          3.14790687]),
 array([ 12.        , 464.80541992,  86.        , 348.60406494,
          2.25243387]),
 array([ 13.        , 552.76708984,  73.        , 414.57531738,
          3.33344141]),
 array([ 15.        , 885.53265381,  91.        , 664.14949036,
          2.73865858]),
 array([ 20.        , 383.95730591,  85.        , 287.96797943,
          5.56994791]),
 array([ 21.        , 444.5027771 ,  51.        , 333.37708282,
          5.22669408]),
 array([  22.        , 1308.5489

In [240]:
z_form_test.append(subid[:10])

In [249]:
z_form_test

[array([  2.        , 306.27947998,  53.        , 229.70960999,
         10.46758803]),
 array([  3.        , 489.82223511,  88.        , 367.36667633,
          3.04289686]),
 array([  4.        , 439.21560669,  87.        , 329.41170502,
          7.05297605]),
 array([  7.        , 426.41589355,  87.        , 319.81192017,
          1.97862841]),
 array([  8.        , 678.11975098,  88.        , 508.58981323,
          3.39115355]),
 array([  9.        , 496.75585938,  91.        , 372.56689453,
          3.14790687]),
 array([ 12.        , 464.80541992,  86.        , 348.60406494,
          2.25243387]),
 array([ 13.        , 552.76708984,  73.        , 414.57531738,
          3.33344141]),
 array([ 15.        , 885.53265381,  91.        , 664.14949036,
          2.73865858]),
 array([ 20.        , 383.95730591,  85.        , 287.96797943,
          5.56994791]),
 array([ 21.        , 444.5027771 ,  51.        , 333.37708282,
          5.22669408]),
 array([  22.        , 1308.5489

In [ ]:
z_form_new = []
for i in range(20):
    vform =  vpeak[i] * 0.75
    print('The vpeak is %s'%(vpeak[i]))
    print('The vform is %s'%(vform))
    print('The vpeak snapshot is %s'%vpeaksnap[i])
    for j in range(100):
        if subid[i] <= len_all[j] -1:
            print('The birthsnap of %dth subhalo is %d'%(subid[i],j))
            print('The birthsnap check is %d'%(vmax[j][subid[i]][2]))
            print('j = %d'%j)

            for k in range(j,vpeaksnap[i]):
                
#                 vmax_evo = vmax[k][subid[i]][1]
#                 print('The vmax is %s'%vmax_evo)
#                 vmax_evo_1 = vmax[k+1][subid[i]][1]
#                 print('The vmax of next snapshot is %s'%vmax_evo_1)
                
                if vform < vmax[k][subid[i]][1]:
                    snap_bir = j
                    print('The snapshot of birth is %s'%snap_bir)
                    print('The vmax is %s'%vmax[k][subid[i]][1])
                    z_form = redshift[j]
                    print('The redshift is %s'%z_form)
                    break
#                 elif vmax_evo <= vform < vmax_evo_1 :
                elif vmax[k][subid[i]][1] <= vform < vmax[k+1][subid[i]][1]:
#                     snap_bir = k
                    print('The snapshot of interpretation is between %s and %s .'%(k,k+1))
                    print('The first redshift is %s'%(redshift[k]))
                    print('The next redshift is %s'%(redshift[k+1]))
                    print('The first vmax is %s'%(vmax[k][subid[i]][1]))
                    print('The next vmax is %s'%(vmax[k+1][subid[i]][1]))
                    interp_v = [vmax[k][subid[i]][1],vmax[k+1][subid[i]][1]]
                    interp_z = [redshift[k],redshift[k+1]]
                    red_new = np.interp(vform,interp_v,interp_z)
#                     form_all = np.array((subid[i],vpeak[i],vpeaksnap[i],vform,red_new))
#                     z_form.append(form_all)
                    print('The interplated redshift is %s'%red_new)
                    break
#                 print('The circle number is %s'%k)
            form_all = np.array((subid[i],vpeak[i],vpeaksnap[i],vform,red_new))
            z_form_new.append(form_all)
#             print('j = %d'%j)
            break
# print(z_form)
        
            

        





In [106]:
# for i in range(0,100):
#     filein='/home/cossim/CosmicGrowth/6610/subcsubhaloaloSize/HaloSize_%d.hdf5' % i
#     halos=h5py.File(filein,'r')['HostHalos'][...]
#     Mvir=halos['MVir']
#     HaloID=halos['HaloId']
#     fileout='/home/yunzheng/mock/orphan/halosize/hosthalo_%d.dat' % i
#     data=np.stack((HaloID,Mvir),axis=-1)
#     np.savetxt(fileout, data,fmt='%1.6e')